version: '3'

services:
  mysql-standalone1:
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=devicedb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - devicedb-data:/var/lib/mysql
  mysql-standalone2:
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=certificatedb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - certificatedb-data:/var/lib/mysql
  my-eureka-server:
    image: meghakakkar/test_1:my-eureka-server
    ports: 
      - 8761:8761
  my-eureka-client1:
    image: meghakakkar/test_1:my-eureka-client1
    ports:
      - 8081:8081
    depends_on:
      - mysql-standalone1
      - my-eureka-server
  my-eureka-client2:
    image: meghakakkar/test_1:my-eureka-client2
    ports:
      - 8082:8082
    depends_on:
      - mysql-standalone2
      - my-eureka-server
  my-api-gateway:
    image: my-api-gateway
    ports:
      - 8083:8083
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - my-eureka-server
      - my-eureka-client1
      - my-eureka-client2
volumes:
  devicedb-data:
  certificatedb-data:
