server:
  port: 8083
  
spring:
  application:
    name: API_GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: DEVICE-SERVICE
        uri:
          http://my-eureka-client1:8081
        predicates:
        - Path=/device/**
        
      - id: CERTIFICATE-SERVICE
        uri:
          http://my-eureka-client2:8082
        predicates:
        - Path=/certificate/**
